/*
** File:	vbe_boot.h
**
** Author:	James Letendre
**
** Contributor:
**
** Description:	VBE bootstrap code
*/
#ifndef VBE_BOOT_H
#define VBE_BOOT_H

/* offsets for vbe info mode block */
#define VBE_INFO_SIGNATURE		0
#define VBE_INFO_VERSION		4
#define VBE_INFO_OEM_STR_PTR	6
#define VBE_INFO_CAPABILITIES	10
#define VBE_INFO_VIDEO_MODE_PTR	14
#define VBE_INFO_TOTAL_MEM		18
#define VBE_INFO_OEM_SW_REV		20
#define VBE_INFO_OEM_VEND_NAME	22
#define VBE_INFO_PRODUCT_NAME	26
#define VBE_INFO_PRODUCT_REV	30
#define VBE_INFO_RESERVED		34
#define VBE_INFO_OEM_DATA		256

/* offsets for vbe mode info block */
#define VBE_MODE_INFO_MODE_ATTRIB	0
#define VBE_MODE_INFO_WINA_ATTRIB	2
#define VBE_MODE_INFO_WINB_ATTRIB	3
#define VBE_MODE_INFO_WIN_GRAN		4
#define VBE_MODE_INFO_WIN_SIZE		6
#define VBE_MODE_INFO_WINA_SEG		8
#define VBE_MODE_INFO_WINB_SEG		10
#define VBE_MODE_INFO_WIN_FUNC_PTR	12
#define VBE_MODE_INFO_BYTE_PER_LINE	16
#define VBE_MODE_INFO_X_RES			18
#define VBE_MODE_INFO_Y_RES			20
#define VBE_MODE_INFO_X_CHAR_SIZE	22
#define VBE_MODE_INFO_Y_CHAR_SIZE	23
#define VBE_MODE_INFO_NUM_PLANES	24
#define VBE_MODE_INFO_BPP			25
#define VBE_MODE_INFO_NUM_BANKS		26
#define VBE_MODE_INFO_MEM_MODEL		27
#define VBE_MODE_INFO_BANK_SIZE		28
#define VBE_MODE_INFO_NUM_IMG_PAGE	29
#define VBE_MODE_INFO_RESV_1		30
#define VBE_MODE_INFO_RED_MASK_SIZE	31
#define VBE_MODE_INFO_RED_FIELD_POS	32
#define VBE_MODE_INFO_GREEN_MASK_SIZE	33
#define VBE_MODE_INFO_GREEEN_FIELD_POS	34
#define VBE_MODE_INFO_BLUE_MASK_SIZE	35
#define VBE_MODE_INFO_BLUE_FIELD_POS	36
#define VBE_MODE_INFO_RSVD_MASK_SIZE	37
#define VBE_MODE_INFO_RSVD_FIELD_POS	38
#define VBE_MODE_INFO_DIRECT_COLOR_MODE_INFO	39
#define VBE_MODE_INFO_PHYS_BASE_PTR	40
#define VBE_MODE_INFO_RESV_2		44
#define VBE_MODE_INFO_RESV_3		48
#define VBE_MODE_INFO_LIN_BYTES_PER_LINE	50
#define VBE_MODE_INFO_BANK_NUM_IMAGES	52
#define VBE_MODE_INFO_LIN_NUM_IMAGES	53
#define VBE_MODE_INFO_LIN_RED_MASK_SIZE	54
#define VBE_MODE_INFO_LIN_RED_FIELD_POS	55
#define VBE_MODE_INFO_LIN_GREEN_MASK_SIZE	56
#define VBE_MODE_INFO_LIN_GREEN_FIELD_POS	57
#define VBE_MODE_INFO_LIN_BLUE_MASK_SIZE	58
#define VBE_MODE_INFO_LIN_BLUE_FIELD_POS	59
#define VBE_MODE_INFO_LIN_RSVD_MASK_SIZE	58
#define VBE_MODE_INFO_LIN_RSVD_FIELD_POS	59
#define VBE_MODE_INFO_MAX_PIXEL_CLK	60
#define VBE_MODE_INFO_RSVD_4		64

#endif

